In [1]:
!pip uninstall -y numpy gensim
!pip install numpy==1.26.4
!pip install --no-cache-dir --force-reinstall gensim


Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: gensim 4.3.3
Uninstalling gensim-4.3.3:
  Successfully uninstalled gensim-4.3.3
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 91.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 28.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 235.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 230.2 MB/s eta 0:0

**FastText**

In [2]:
import numpy
print("NumPy version:", numpy.__version__)

NumPy version: 1.26.4


In [3]:
from gensim.models import FastText
print("Gensim is ready!")

Gensim is ready!


In [4]:
with open("/content/sample_data/01 Harry Potter and the Sorcerers Stone.txt","r") as f:
  text = f.read()

In [5]:
import re
processed_text = re.sub('[^A-Za-z. ]','',text)


In [ ]:
# here also , we will make/split the data into list of list

In [6]:
text_list = processed_text.split('.')
text_list[0]

'M r'

In [7]:
sentences = [text.split() for text in text_list]
sentences[0]

['M', 'r']

In [8]:
sentences[0:2]

[['M', 'r'], ['and', 'Mrs']]

In [10]:
model = FastText(vector_size=100, window=5, min_count=1)


In [11]:
model.build_vocab(sentences) # building the vocab

In [20]:
model.wv.key_to_index # vocab has been build and and ID is assigned to each word

In [14]:
#sg not passed , so be default sg=0, means CBOW
model.train(corpus_iterable=sentences, epochs=10, total_examples=len(sentences))

(606867, 768580)

In [17]:
model.wv['Harry']

array([ 0.02038177,  0.14037593, -0.8447632 ,  0.06858952,  0.2664796 ,
        0.4351732 , -0.61260015,  0.20498033,  0.45005748, -0.12681022,
        0.32203272, -0.05782613, -0.616444  ,  1.6743722 , -0.8074099 ,
       -0.10746881,  0.46297932, -0.19813004, -0.69047827, -0.50429267,
       -1.0636194 ,  0.25492242, -0.48669487, -0.3511881 , -0.45102748,
       -0.72869706, -0.6630939 , -0.5069769 , -0.04488607,  0.2205369 ,
       -0.68490446,  0.11561207,  1.4919833 , -0.31468529,  0.25406784,
        0.7899553 , -0.26971737,  0.25777227,  0.0060927 , -0.23166221,
        0.30163664, -0.37667218,  0.04942961, -0.38878328, -0.30642885,
       -0.6102699 , -0.7424356 ,  0.38356158,  0.85617393,  0.22462921,
        0.32795566, -0.42021996,  0.6167248 , -0.46802208, -0.46152002,
        0.18359381,  0.29531878,  0.4190588 , -0.20023671, -0.32002488,
        0.11260318, -0.59321   , -0.2093152 ,  0.95055014, -0.38866785,
        0.7321192 , -0.28349304,  0.3837497 ,  0.3376593 ,  0.44

In [18]:
model.wv['harry'] # observe that even small case harry has got the embedding, this case is handled here

array([ 0.02111514,  0.14269748, -0.8364933 ,  0.05832774,  0.23541848,
        0.39993855, -0.5538536 ,  0.2673312 ,  0.5062167 , -0.18084295,
        0.23898503, -0.04031714, -0.58314216,  1.5657905 , -0.745968  ,
       -0.11345426,  0.43610415, -0.21901157, -0.7744574 , -0.5384722 ,
       -1.0325626 ,  0.24807014, -0.3691976 , -0.37665796, -0.44535992,
       -0.6329736 , -0.6463763 , -0.4645145 , -0.01605343,  0.25363687,
       -0.69956654,  0.138093  ,  1.3917965 , -0.2659603 ,  0.24925283,
        0.75502163, -0.2413257 ,  0.29676345,  0.00192095, -0.21559967,
        0.23472418, -0.35986677,  0.04497727, -0.3234673 , -0.38165888,
       -0.5831309 , -0.66216713,  0.38344356,  0.8283636 ,  0.1832556 ,
        0.31629965, -0.3438831 ,  0.5712334 , -0.41876513, -0.45845112,
        0.10575414,  0.22474381,  0.36583897, -0.20483579, -0.3061541 ,
        0.10686674, -0.5872969 , -0.2166504 ,  0.938456  , -0.32908288,
        0.7045468 , -0.24509116,  0.29507476,  0.3512828 ,  0.38

In [19]:
model.wv.most_similar('harry')

[('hurry', 0.9999046325683594),
 ('raspberry', 0.999899685382843),
 ('readyHarry', 0.9998835921287537),
 ('carry', 0.9998627305030823),
 ('HotelCokeworthHarry', 0.9998553991317749),
 ('cry', 0.9998498558998108),
 ('dry', 0.9998309016227722),
 ('furioushe', 0.9998235702514648),
 ('mione', 0.9998202323913574),
 ('Hardly', 0.999816358089447)]

In [ ]:
# lets understand the Hyperparameters now
min_n
minimum size of character split, n gram

max_n
max size of character split , n gram

sentences(required):
  input data ,where each sentences represented as list of Words

vector size (default =100):
  dimensionality of vector

window (default = 5)
  maximum distance between the context word and focus word

min_count(default = 5)
  min freq of word

workers(default = 3)
  no of cpu cores to use for training

alpha (default = 0.025)
  initial learning rate , this starts reducing as we start the training, deep learning Concept

min_alpha(default = 0.001)
  learning rate will linearly drop to this value

epochs(default=5):
  no of iterations over the corpus/dataset

sg(default=0)
  sg=0 --> CBOW
  sg=1 --> skipgram

**Doc2Vec**

In [ ]:
# two ways to train Doc2Vec
# 1. Distributed Memory (DM) ---- Skip Gram
# 2. Distributed Bag of Words(DBOW) ---- CBOW

In [22]:
from gensim.models import doc2vec
from gensim.models.doc2vec import TaggedDocument,Doc2Vec # tagged docuument will give id to each doc

In [24]:
# We will pass id with each document while creatin the data set
# data format required is list of sentences
# [sent1,sent2,sent3,...]

In [25]:
data = processed_text.split(".")
data[0]

'M r'

In [32]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [30]:
from nltk.tokenize import word_tokenize

In [ ]:
# creating ID for the data

# for id,sent in enumerate(data):
#   TaggedDocument(words=word_tokenize(sent),tags=[id])

In [33]:
#same thing in list comprehension
tagged_data = [TaggedDocument(words=word_tokenize(sent),tags=[id]) for id,sent in enumerate(data)]

In [35]:
tagged_data[1]

TaggedDocument(words=['and', 'Mrs'], tags=[1])

In [37]:
model_doc2vec = Doc2Vec(vector_size=100, min_count=1, epochs=10)

In [38]:
model_doc2vec.build_vocab(tagged_data)

In [40]:
model_doc2vec.wv.key_to_index # this is for checking the vocab

In [41]:
model_doc2vec.train(tagged_data, total_examples=model_doc2vec.corpus_count, epochs=model_doc2vec.epochs)

In [42]:
model_doc2vec.wv['Harry']

array([-2.8015128e-01,  3.2952562e-01, -3.9512381e-02,  2.8886247e-02,
        1.1008927e-01, -6.8249160e-01,  3.5516661e-01,  1.5037049e+00,
       -9.0411371e-01, -8.7001419e-01, -1.2941584e-01, -1.2102170e+00,
        1.4036667e-01,  6.0865688e-01,  1.4884241e-01, -5.5648679e-01,
        7.9308313e-01, -4.3946281e-01, -3.2487875e-01, -1.7280539e+00,
        2.5831115e-01,  3.1108004e-01,  5.3474551e-01, -2.7908468e-01,
       -4.3872561e-02,  7.1471542e-02, -2.0113114e-01, -8.7458342e-02,
       -6.7241168e-01,  3.5044837e-01,  7.8639090e-01, -7.8170106e-02,
        7.5019158e-02, -3.2356721e-01,  6.2437574e-03,  8.0037040e-01,
        4.5444557e-01, -4.5498019e-01, -2.9286438e-01, -6.9295818e-01,
        3.5306808e-01, -6.3552654e-01, -4.5528102e-01, -1.6834325e-01,
        7.9696941e-01, -8.0420281e-04, -7.1122009e-01, -3.3835733e-01,
        2.7395102e-01,  6.4784354e-01,  1.6049127e-01, -4.4565535e-01,
       -1.0646313e-02, -1.6660267e-01, -3.0191970e-01,  3.4536281e-01,
      

In [54]:
tagged_data[10]  # this is the whole one document with id 10

TaggedDocument(words=['The', 'Dursleys', 'had', 'everything', 'they', 'wanted', 'but', 'they', 'also', 'had', 'a', 'secret', 'and', 'their', 'greatest', 'fear', 'was', 'that', 'somebody', 'would', 'discover', 'it'], tags=[10])

In [55]:
model_doc2vec.docvecs[10] # this is the vector rep of the whole doc of id 10

<ipython-input-55-9a2e1f0df3a4>:1: DeprecationWarning: Call to deprecated `docvecs` (The `docvecs` property has been renamed `dv`.).
  model_doc2vec.docvecs[10] # this is the vector rep of the whole doc of id 1


array([-0.00993139, -0.00082763,  0.00562577, -0.00462139, -0.00565077,
       -0.00706789,  0.01897665,  0.03130152, -0.01095526, -0.014591  ,
       -0.01016433, -0.02706053,  0.0006693 ,  0.01190737, -0.0067475 ,
       -0.02016668,  0.01582433,  0.00186781, -0.01024804, -0.02515985,
        0.00984423,  0.0016419 ,  0.00161595, -0.01279073, -0.00687826,
       -0.00727758, -0.01231115, -0.00660084, -0.0130501 , -0.00057491,
        0.01403275,  0.00339821, -0.00749848, -0.01352415, -0.00330817,
        0.02488692,  0.01056773, -0.01738856, -0.00646789, -0.00852286,
        0.01186462, -0.01789384, -0.01309671, -0.00200106,  0.02279664,
       -0.00769964, -0.00874139, -0.00964629,  0.00839197,  0.0104785 ,
        0.01327129, -0.01657651,  0.01115337, -0.00346192,  0.00021757,
        0.01935864,  0.00871703, -0.00610844, -0.01455021, -0.00448274,
        0.01526225,  0.00862812,  0.00294086, -0.00454124, -0.00516553,
        0.02324459, -0.01348888,  0.00693043, -0.01602082,  0.01

In [56]:
# now lets check the vect of the words of those document
model_doc2vec.infer_vector(['The', 'Dursleys', 'had', 'everything', 'they', 'wanted', 'but', 'they', 'also', 'had', 'a', 'secret', 'and', 'their', 'greatest', 'fear', 'was', 'that', 'somebody', 'would', 'discover', 'it'])

array([-0.02138517,  0.0085051 , -0.0068702 , -0.00695647, -0.00143623,
       -0.02797327,  0.02464352,  0.0523371 , -0.03204389, -0.03012031,
       -0.01050111, -0.04003914,  0.0004062 ,  0.01734932,  0.00740383,
       -0.03009528,  0.03292181, -0.01699536, -0.01785105, -0.04810462,
        0.01241878,  0.00198116,  0.00773203, -0.00773035, -0.00947753,
       -0.00216195, -0.00989431, -0.02586042, -0.02402024,  0.01204816,
        0.0312595 ,  0.00048369,  0.00958502, -0.0140547 ,  0.01203423,
        0.02347988,  0.01787592, -0.01683742, -0.00628502, -0.03618919,
        0.01481801, -0.02065617, -0.01706614,  0.00206232,  0.02318159,
       -0.01349603, -0.0173824 ,  0.00053159,  0.01022405,  0.02253202,
        0.00523384, -0.01212152,  0.00417942, -0.00360151, -0.01477541,
        0.02252605,  0.02151278, -0.0011343 , -0.01918185,  0.00375121,
        0.03843005, -0.00431246,  0.00409515,  0.00592127, -0.01693031,
        0.03649382, -0.01908113,  0.02760811, -0.03442815,  0.00

In [57]:
new_doc = model_doc2vec.infer_vector(['The', 'Dursleys', 'had', 'everything', 'they', 'wanted', 'but', 'they', 'also', 'had', 'a', 'secret', 'and', 'their', 'greatest', 'fear', 'was', 'that', 'somebody', 'would', 'discover', 'it'])

In [58]:
# so here we should have gotten the same  id i.e 10, but due to shorter data, it has given other ids
model_doc2vec.docvecs.most_similar(new_doc)

<ipython-input-58-67b0b3aa739f>:2: DeprecationWarning: Call to deprecated `docvecs` (The `docvecs` property has been renamed `dv`.).
  model_doc2vec.docvecs.most_similar(new_doc)


[(3845, 0.9641897082328796),
 (3091, 0.9638416171073914),
 (1050, 0.963324785232544),
 (3433, 0.9614928960800171),
 (3621, 0.9607818722724915),
 (4523, 0.9601372480392456),
 (666, 0.9597435593605042),
 (1054, 0.9596314430236816),
 (1206, 0.9593465328216553),
 (250, 0.9587805867195129)]

In [ ]:
# use case can be like, if you have got new review document or any document, and you want to
# check which doc is the most similar, so from the above approach, we can find out