In [1]:
!pip uninstall -y numpy gensim
!pip install numpy==1.26.4
!pip install --no-cache-dir --force-reinstall gensim


Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: gensim 4.3.3
Uninstalling gensim-4.3.3:
  Successfully uninstalled gensim-4.3.3
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 201.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 290.6 MB/s eta 0:00:

In [42]:
import numpy
print("NumPy version:", numpy.__version__)

from gensim.models import Word2Vec
print("Gensim is ready!")


NumPy version: 1.26.4
Gensim is ready!


In [4]:
with open("/01 Harry Potter and the Sorcerers Stone.txt","r") as f:
  text = f.read()

In [7]:
text

"M r. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you’d expect to be involved in anything strange or mysterious, because they just didn’t hold with such nonsense.\n\nMr. Dursley was the director of a firm called Grunnings, which made drills. He was a big, beefy man with hardly any neck, although he did have a very large mustache. Mrs. Dursley was thin and blonde and had nearly twice the usual amount of neck, which came in very useful as she spent so much of her time craning over garden fences, spying on the neighbors. The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere.\n\nThe Dursleys had everything they wanted, but they also had a secret, and their greatest fear was that somebody would discover it. They didn’t think they could bear it if anyone found out about the Potters. Mrs. Potter was Mrs. Dursley’s sister, but they hadn’t met for sever

In [14]:
# preprocessing(we can do multiple preprocessing but here just for learning we are doing only 1 step of preprocessing  )

In [8]:
import re

In [10]:
processed_text = re.sub('[^A-Za-z. ]','',text)

In [13]:
processed_text

'M r. and Mrs. Dursley of number four Privet Drive were proud to say that they were perfectly normal thank you very much. They were the last people youd expect to be involved in anything strange or mysterious because they just didnt hold with such nonsense.Mr. Dursley was the director of a firm called Grunnings which made drills. He was a big beefy man with hardly any neck although he did have a very large mustache. Mrs. Dursley was thin and blonde and had nearly twice the usual amount of neck which came in very useful as she spent so much of her time craning over garden fences spying on the neighbors. The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere.The Dursleys had everything they wanted but they also had a secret and their greatest fear was that somebody would discover it. They didnt think they could bear it if anyone found out about the Potters. Mrs. Potter was Mrs. Dursleys sister but they hadnt met for several years in fact Mrs. Durs

In [ ]:
# word2vec require data in a specific format like below
#[[word1sent1,word2sent1],[word1sent2,word2sent2]] ...and so on

In [16]:
text_list = processed_text.split('.')

In [17]:
text_list[:10]

['M r',
 ' and Mrs',
 ' Dursley of number four Privet Drive were proud to say that they were perfectly normal thank you very much',
 ' They were the last people youd expect to be involved in anything strange or mysterious because they just didnt hold with such nonsense',
 'Mr',
 ' Dursley was the director of a firm called Grunnings which made drills',
 ' He was a big beefy man with hardly any neck although he did have a very large mustache',
 ' Mrs',
 ' Dursley was thin and blonde and had nearly twice the usual amount of neck which came in very useful as she spent so much of her time craning over garden fences spying on the neighbors',
 ' The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere']

In [26]:
# now we have a list of all the sentences, and now we want the list of all the words in a sentence
sentences_list = [sent.split() for sent in text_list]

In [27]:
len(sentences_list)

5419

In [ ]:
#creating model object

In [ ]:
#here sg parameter means skip gram , by default [sg=0, means,CBOW method] [sg=1, means skipgram method, this is 2nd architecture of sg]
#vector_size = dimension of the embedding required,(hidden layer neuron will be decided)
#window=5, this is by defaultn is 5, means how many words to be prdeicted in left and right
#min_count=1, 1 is by default, means, the minimum how many times the word should occur in the vocab (if min_count=10, means, all the words whose,
#     count is less than 10 will not be used for the processing, but since we have used 1, that means, even if any word has occured only once in
#     the vocab, still we will be considering that word for processing)

In [28]:
model = Word2Vec(sentences=sentences_list,sg=1,vector_size=100,window=5,min_count=1)

In [29]:
print(model.wv.index_to_key) # this is the vocab/unique words

['the', 'to', 'and', 'a', 'of', 'was', 'Harry', 'he', 'in', 'his', 'said', 'it', 'you', 'had', 'I', 'on', 'at', 'that', 'him', 'as', 'He', 'they', 'with', 'Ron', 'but', 'be', 'up', 'out', 'for', 'all', 'were', 'them', 'Hagrid', 'have', 'The', 'back', 'Hermione', 'what', 'from', 'one', 'into', 'about', 'been', 'It', 'their', 'an', 'not', 'this', 'me', 'off', 'if', 'there', 'didnt', 'could', 'so', 'like', 'got', 'get', 'know', 'Professor', 'down', 'her', 'she', 'its', 'looked', 'over', 'is', 'very', 'just', 'see', 'They', 'who', 'do', 'by', 'around', 'Snape', 'when', 'are', 'Dumbledore', 'your', 'no', 'going', 'now', 'think', 'through', 'time', 'Im', 'hed', 'then', 'Dudley', 'You', 'something', 'we', 'go', 'never', 'Harrys', 'dont', 'Uncle', 'more', 'Malfoy', 'here', 'right', 'would', 'door', 'first', 'eyes', 'Vernon', 'couldnt', 'again', 'only', 'look', 'before', 'And', 'Neville', 'looking', 'But', 'Potter', 'head', 'or', 'too', 'thought', 'than', 'A', 'did', 'way', 'McGonagall', 'even'

In [30]:
#now we can check the vectors of any word we want.
#vector of word 'Harry' is as below , len of this vector will be 100 , as we already defined while creating the model object
model.wv['Harry']

array([ 7.47376308e-02,  8.31603855e-02,  4.93131578e-02,  1.55071303e-01,
       -3.30880657e-02, -2.14934811e-01,  2.29058027e-01,  3.30670387e-01,
       -2.95539081e-01, -1.48114055e-01, -6.92686737e-02, -2.48682439e-01,
        2.24210531e-01,  9.39561054e-02, -5.62613681e-02, -2.18548492e-01,
        3.74395162e-01, -1.82229728e-01, -1.35948554e-01, -6.02115571e-01,
        2.25883245e-01,  1.45217463e-01,  2.02723831e-01, -6.32521063e-02,
       -5.05788699e-02,  1.98222771e-01, -1.37113303e-01,  1.32136270e-02,
       -2.52621442e-01,  7.91872516e-02,  3.14903766e-01,  1.01712812e-03,
        4.41855453e-02, -1.72149599e-01, -4.65570204e-02,  2.57856876e-01,
       -3.22958198e-03, -2.39161253e-01, -3.47947687e-01, -2.20402405e-01,
        2.91740354e-02, -2.30870768e-01, -2.22128853e-01,  2.60519404e-02,
        2.39762604e-01, -7.68447593e-02, -2.29269326e-01, -2.06823528e-01,
        1.52504202e-02,  4.28380333e-02,  9.95981682e-05, -3.55684042e-01,
       -1.44575372e-01, -

In [31]:
len(model.wv['Harry'])

100

In [32]:
# to check the most similar word
model.wv.most_similar('Harry')

[('Hermione', 0.9824188351631165),
 ('Ron', 0.9786530137062073),
 ('Hagrid', 0.9718433022499084),
 ('she', 0.9683980345726013),
 ('Neville', 0.9619025588035583),
 ('Malfoy', 0.9567053914070129),
 ('looking', 0.9533975720405579),
 ('again', 0.9508718252182007),
 ('still', 0.9470714926719666),
 ('once', 0.944216787815094)]

In [33]:
# now to save this model
model.save('harry_word2vec_100dim.model')

In [44]:
# to load the model
loaded_model = Word2Vec.load('/content/harry_word2vec_100dim.model')

In [38]:
#now check the loaded model
loaded_model.wv.most_similar('Harry')

[('Hermione', 0.9824188351631165),
 ('Ron', 0.9786530137062073),
 ('Hagrid', 0.9718433022499084),
 ('she', 0.9683980345726013),
 ('Neville', 0.9619025588035583),
 ('Malfoy', 0.9567053914070129),
 ('looking', 0.9533975720405579),
 ('again', 0.9508718252182007),
 ('still', 0.9470714926719666),
 ('once', 0.944216787815094)]

In [ ]:
#retraining the model below on new data

In [39]:
#now we will check how can we create embeddings of new data from this same model,
# for that we will list down all the required parameters which we used while training this model

In [ ]:
# model = Word2Vec(sentences=sentences_list,sg=1,vector_size=100,window=5,min_count=1)
#these were all the parameters used

sentences(required):
  input data ,where each sentences represented as list of Words

vector size (default =100):
  dimensionality of vector

window (default = 5)
  maximum distance between the context word and focus word

min_count(default = 5)
  min freq of word

workers(default = 3)
  no of cpu cores to use for training

alpha (default = 0.025)
  initial learning rate , this starts reducing as we start the training, deep learning Concept

min_alpha(default = 0.001)
  learning rate will linearly drop to this value

epochs(default=5):
  no of iterations over the corpus/dataset

sg(default=0)
  sg=0 --> CBOW
  sg=1 --> skipgram


In [45]:
prev_model = Word2Vec.load('/content/harry_word2vec_100dim.model')

In [46]:
prev_model.wv['ron'] # we can see here , that vector of small case "ron" is not there in current model

KeyError: "Key 'ron' not present"

In [ ]:
# now we will create a dummy dataset in which we will keep small case words,
# which we did not do in the preprocessing of previous model, and will train these new dataset with our
# already trained model

In [47]:
new_sents = [['ron','harry','hermoine'],['ron','harry','hermoine']]
# we are adding three new words in the vocab/unique words

In [48]:
# checking the length of vocab in prev model
len(prev_model.wv.index_to_key)

7438

In [49]:
# adding the new three words
prev_model.build_vocab(new_sents,update=True)

In [50]:
# now we will check the length of the voacb after adding three new words
len(prev_model.wv.index_to_key)

7441

In [51]:
# so we can see that new three words are added in the vocab

prev_model.wv['ron']
# here we have got the embeddings before training but these are just randmoly intiliased numbers

array([-7.5078728e-03,  5.1972615e-03,  1.5247095e-03, -5.5726324e-03,
        7.1157753e-03, -8.3695985e-03,  9.8515544e-03,  2.9579329e-03,
       -2.8075515e-03,  6.1461390e-03, -2.9793715e-03, -2.6137054e-03,
        7.1882606e-03, -7.5378753e-03, -3.3744955e-03, -7.7868998e-03,
        7.1479296e-03,  8.6283032e-03, -3.0842328e-03,  7.8473780e-03,
        4.6920287e-03,  9.4072614e-03, -9.1912756e-03,  7.0496025e-03,
       -4.7891139e-05, -2.0877088e-03,  9.9775353e-03,  1.0768009e-03,
       -4.0520597e-03,  8.2503560e-05,  8.3749900e-03, -5.3347587e-03,
        6.8384800e-03, -5.9088157e-03,  7.2790934e-03,  6.2741018e-03,
       -7.6512466e-03,  5.5579152e-03, -3.1956553e-03,  5.6417082e-03,
       -8.7189591e-03,  3.5977005e-03, -7.0121097e-03,  2.1281682e-03,
        1.0684908e-03, -5.5731130e-03, -2.5549328e-03,  9.4145080e-03,
        5.5135679e-03, -3.2949387e-03, -9.3827974e-03,  2.8880693e-03,
       -2.1831607e-03, -9.7504379e-03,  5.7831919e-03, -8.1949793e-03,
      

In [53]:
prev_model.train(new_sents,total_examples=prev_model.corpus_count,epochs=prev_model.epochs)

(3, 30)

In [54]:
prev_model.wv['ron']
# now these are the actual vectors, might be looking similar to the earlier
# but these is becuse we didnt trained on enough data to give model much context.

array([-7.5078728e-03,  5.1972615e-03,  1.5247095e-03, -5.5726324e-03,
        7.1157753e-03, -8.3695985e-03,  9.8515544e-03,  2.9579329e-03,
       -2.8075515e-03,  6.1461390e-03, -2.9793715e-03, -2.6137054e-03,
        7.1882606e-03, -7.5378753e-03, -3.3744955e-03, -7.7868998e-03,
        7.1479296e-03,  8.6283032e-03, -3.0842328e-03,  7.8473780e-03,
        4.6920287e-03,  9.4072614e-03, -9.1912756e-03,  7.0496025e-03,
       -4.7891139e-05, -2.0877088e-03,  9.9775353e-03,  1.0768009e-03,
       -4.0520597e-03,  8.2503560e-05,  8.3749900e-03, -5.3347587e-03,
        6.8384800e-03, -5.9088157e-03,  7.2790934e-03,  6.2741018e-03,
       -7.6512466e-03,  5.5579152e-03, -3.1956553e-03,  5.6417082e-03,
       -8.7189591e-03,  3.5977005e-03, -7.0121097e-03,  2.1281682e-03,
        1.0684908e-03, -5.5731130e-03, -2.5549328e-03,  9.4145080e-03,
        5.5135679e-03, -3.2949387e-03, -9.3827974e-03,  2.8880693e-03,
       -2.1831607e-03, -9.7504379e-03,  5.7831919e-03, -8.1949793e-03,
      

In [55]:
prev_model.save("new_harry_word2vec_100dim.model")

In [56]:
# keep and pay attention for Version control of the data,preprocessing done,parameters used while training,
# model saved. VCS is important here